import './App.css'

function App() {

    return (
        <div id='app' className='center-element'>
            <div className='container'>
                <div className="header center-element">
                    header
                </div>
                <div className='body'>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>
                    <div>
                        aaaaaaaaaaaa
                    </div>

                </div>
                <div className="nav center-element">
                    navigate
                </div>
            </div>
        </div>
    )
}

export default App
